In [1]:
import numpy as np
from triangle_intersection import py_segment_triangle_intersection, py_segment_triangle_intersection_grad

In [2]:
T1 = np.array([0., 0., 0.])
T2 = np.array([1., 0., 0.])
T3 = np.array([0., 1., 0.])
S1 = np.array([0.2, 0.2, -1.0])
S2 = np.array([0.2, 0.2, 1.0])

intersect, I = py_segment_triangle_intersection(T1, T2, T3, S1, S2)
print(intersect)
print(I)


True
[0.2 0.2 0. ]


In [3]:
n_dv = 15
T1_grad = np.zeros((3, n_dv))
T1_grad[0, 0] = 1.
T1_grad[1, 1] = 1.
T1_grad[2, 2] = 1.
T2_grad = np.zeros((3, n_dv))
T2_grad[0, 3] = 1.
T2_grad[1, 4] = 1.
T2_grad[2, 5] = 1.
T3_grad = np.zeros((3, n_dv))
T3_grad[0, 6] = 1.
T3_grad[1, 7] = 1.
T3_grad[2, 8] = 1.
S1_grad = np.zeros((3, n_dv))
S1_grad[0, 9] = 1.
S1_grad[1, 10] = 1.
S1_grad[2, 11] = 1.
S2_grad = np.zeros((3, n_dv))
S2_grad[0, 12] = 1.
S2_grad[1, 13] = 1.
S2_grad[2, 14] = 1.

I_grad = py_segment_triangle_intersection_grad(T1, T2, T3, T1_grad, T2_grad, T3_grad, S1, S2, S1_grad, S2_grad)
print(I_grad)




[[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.5 0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.5 0.  0.  0.5 0. ]
 [0.  0.  0.6 0.  0.  0.2 0.  0.  0.2 0.  0.  0.  0.  0.  0. ]]


In [4]:
def obj(x):
    T1, T2, T3, S1, S2 = np.split(x, 5)
    intersect, I = py_segment_triangle_intersection(T1, T2, T3, S1, S2)
    if intersect:
        return I
    else:
        return np.zeros(3)    

In [5]:
x0 = np.concatenate((T1, T2, T3, S1, S2))
print(obj(x0))

[0.2 0.2 0. ]


In [6]:
def obj_grad(x):
    T1, T2, T3, S1, S2 = np.split(x, 5)
    n_dv = 15
    intersect, _ = py_segment_triangle_intersection(T1, T2, T3, S1, S2)
    if not intersect:
        return np.zeros((3, n_dv))
    T1_grad = np.zeros((3, n_dv))
    T1_grad[0, 0] = 1.
    T1_grad[1, 1] = 1.
    T1_grad[2, 2] = 1.
    T2_grad = np.zeros((3, n_dv))
    T2_grad[0, 3] = 1.
    T2_grad[1, 4] = 1.
    T2_grad[2, 5] = 1.
    T3_grad = np.zeros((3, n_dv))
    T3_grad[0, 6] = 1.
    T3_grad[1, 7] = 1.
    T3_grad[2, 8] = 1.
    S1_grad = np.zeros((3, n_dv))
    S1_grad[0, 9] = 1.
    S1_grad[1, 10] = 1.
    S1_grad[2, 11] = 1.
    S2_grad = np.zeros((3, n_dv))
    S2_grad[0, 12] = 1.
    S2_grad[1, 13] = 1.
    S2_grad[2, 14] = 1.
    return py_segment_triangle_intersection_grad(T1, T2, T3, T1_grad, T2_grad, T3_grad, S1, S2, S1_grad, S2_grad)

In [8]:
obj_grad(x0)

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5, 0. , 0. , 0.5,
        0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5, 0. , 0. ,
        0.5, 0. ],
       [0. , 0. , 0.6, 0. , 0. , 0.2, 0. , 0. , 0.2, 0. , 0. , 0. , 0. ,
        0. , 0. ]])

In [15]:
from scipy.optimize import check_grad
err_grad = check_grad(obj, obj_grad, x0, epsilon=0.005)
print(err_grad)

1.549547557689412e-05


In [19]:
from scipy.optimize import approx_fprime
fd_grad = approx_fprime(x0, obj, epsilon=0.01)
print(fd_grad)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  5.00000000e-01  0.00000000e+00  0.00000000e+00
   5.00000000e-01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  5.00000000e-01  0.00000000e+00
   0.00000000e+00  5.00000000e-01  0.00000000e+00]
 [-5.96046448e-06 -5.96046448e-06  6.00004196e-01  0.00000000e+00
   0.00000000e+00  1.99997425e-01  0.00000000e+00  0.00000000e+00
   1.99997425e-01  0.00000000e+00  0.00000000e+00  3.66568566e-06
   0.00000000e+00  0.00000000e+00 -1.57952310e-06]]


In [34]:
for tirage in range(10000):
    x1 = np.random.rand(15)
    I = obj(x1)
    if np.abs(I).max()>1e-4:
        break

print(tirage, I)
print(x1)
    

9 [0.63245695 0.38177266 0.39637065]
[0.55688136 0.01291897 0.21998288 0.17329453 0.00512863 0.76124447
 0.83138717 0.84617864 0.47039368 0.6646841  0.31713825 0.39706148
 0.38893272 0.87018217 0.39115043]


In [35]:
obj_grad(x1)

array([[ 2.07627687e-01, -1.12134594e-01,  1.45529778e-01,
         5.74618163e-02, -3.10337105e-02,  4.02759661e-02,
         2.11510818e-01, -1.14231777e-01,  1.48251532e-01,
         4.62229809e-01,  2.27317658e-01, -2.95015902e-01,
         6.11698706e-02,  3.00824239e-02, -3.90413729e-02],
       [-4.16415786e-01,  2.24895899e-01, -2.91872909e-01,
        -1.15244782e-01,  6.22408657e-02, -8.07770312e-02,
        -4.24203751e-01,  2.29101985e-01, -2.97331628e-01,
         8.44152173e-01,  4.27223934e-01,  5.91680623e-01,
         1.11712147e-01,  5.65373156e-02,  7.83009448e-02],
       [ 4.45073589e-03, -2.40373272e-03,  3.11959650e-03,
         1.23175946e-03, -6.65242923e-04,  8.63361196e-04,
         4.53397523e-03, -2.44868821e-03,  3.17794039e-03,
        -9.02246863e-03,  4.87281284e-03,  8.76805707e-01,
        -1.19400195e-03,  6.44851012e-04,  1.16033395e-01]])

In [ ]:
approx_fprime(x1, obj, epsilon=0.001)

array([[ 2.07749783e-01, -1.12172022e-01,  1.45861842e-01,
         5.74933488e-02, -3.10436142e-02,  4.02190465e-02,
         2.11271210e-01, -1.14166949e-01,  1.48130019e-01,
         4.61432396e-01,  2.27528531e-01, -2.94659576e-01,
         6.12742621e-02,  3.00512869e-02, -3.90890671e-02],
       [-4.16660662e-01,  2.24970963e-01, -2.92538894e-01,
        -1.15308023e-01,  6.22607285e-02, -8.06628737e-02,
        -4.23723196e-01,  2.28971967e-01, -2.97087924e-01,
         8.42695458e-01,  4.27626131e-01,  5.90965979e-01,
         1.11908612e-01,  5.64907840e-02,  7.83965997e-02],
       [ 4.45335317e-03, -2.40453502e-03,  3.12671468e-03,
         1.23243540e-03, -6.65455220e-04,  8.62141058e-04,
         4.52883896e-03, -2.44729855e-03,  3.17533563e-03,
        -9.00689897e-03,  4.87733315e-03,  8.75744775e-01,
        -1.19610181e-03,  6.44183554e-04,  1.16174128e-01]])

In [50]:
check_grad(obj, obj_grad, x1, epsilon=0.0001)

np.float64(0.00026195297000087447)